spring:
  application:
    name: springboot-vote-api
  datasource:
    url: jdbc:h2:mem:votedb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
